CREATE TABLE ALUNO (
NOME STRING NN KEY,
IDADE INTEGER NN,
CPF INTEGER NN,
INTERESSE STRING,
CODIGO INTEGER NN ORD,
SEILA STRING)
CREATE TABLE FILHO (
NOME STRING NN KEY ORD,
IDADE INTEGER NN,
CPF INTEGER NN,
INTERESSE STRING,
CODIGO INTEGER NN,
SEILA STRING)
INSERT
INTO ALUNO
VALUES (ASSAD, NULO, ', "NULO", 21, ");
INSERT
INTO FILHO
VALUES (PERPETUO, DOIS, '', "NULO", 21, NULO);
INSERT
INTO ALUNO
VALUES (FELIPE, NULO, JS, "NULO", 2434, ");
INSERT
INTO ALUNO
VALUES (JOSE, 234, JESUS, "NULO", 21, ");
SELECT NOME,IDADE,CPF
FROM ALUNO
WHERE NOME=FELIPE;
SELECT NOME,CPF
FROM ALUNO
WHERE IDADE>=23;
SELECT NOME
FROM ALUNO;
SELECT NOME
FROM ALUNO JOIN FILHO ON NOME=NAME;
SELECT NOME
FROM ALUNO JOIN FILHO ON NOME=NAME
WHERE CPF=123456;
