CREATE TABLE ALUNO (
NOME STRING NN KEY,
IDADE INTEGER NN,
CPF INTEGER NN,
INTERESSE STRING,
CODIGO INTEGER NN ORD)
CREATE TABLE FILHO (
NAME STRING NN KEY ORD,
IDADE INTEGER NN,
PAI STRING,
MAE STRING)
CREATE TABLE TESTE (
NOME STRING NN KEY ORD,
CODIGO INTEGER NN ORD,
ATR1 STRING,
ATR2 STRING)
CREATE TABLE TESTE2 (
NOME STRING NN KEY,
CODIGO INTEGER ORD,
ATR1 STRING,
ATR2 STRING)
CREATE TABLE TESTE3 (
NOME STRING KEY,
CODIGO INTEGER NN,
ATR1 STRING,
ATR2 STRING)
INSERT
INTO ALUNO
VALUES ("MICHAEL",21,111,NULO,3);
INSERT
INTO ALUNO
VALUES ("SCHUMACHER",18,521,NULO,1);
INSERT
INTO ALUNO
VALUES ("ALONSO",23,159,NULO,2);
INSERT
INTO ALUNO
VALUES ("MICHAEL",20,201,NULO,5);
INSERT
INTO ALUNO
VALUES (NULO,25,251,NULO,10);
INSERT
INTO ALUNO
VALUES (50,20,201,NULO,5);
INSERT
INTO ALUNO
VALUES ("VETTEL","TESTE",201,NULO,5);
INSERT
INTO FILHO
VALUES ("ALONSO",23,"SENNA","PIQUET");
INSERT
INTO FILHO
VALUES ("SCHUMACHER",18,"VERSTAPPEN","PIQUET");
INSERT
INTO FILHO
VALUES ("VERSTAPPEN",40,"HAMILTON","MALDONADO");
SELECT NOME,IDADE,CPF
FROM ALUNO
WHERE NOME='FELIPE';
SELECT NOME,CPF
FROM ALUNO
WHERE IDADE>=21;
SELECT NOME
FROM ALUNO;
SELECT ANOME,BPAI,BMAE
FROM ALUNO JOIN FILHO ON NOME=NAME;
SELECT ANOME,BPAI,BMAE
FROM ALUNO JOIN FILHO ON NOME=NAME
WHERE IDADE>22;
SELECT A1NAME,A2PAI
FROM FILHO JOIN FILHO ON NAME=NAME;
SELECT A2NAME,A1PAI
FROM FILHO JOIN FILHO ON NAME=PAI;
