CREATE TABLE ALUNO (
NOME STRING NN KEY,
IDADE INTEGER NN,
CPF INTEGER NN,
INTERESSE STRING,
CODIGO INTEGER NN ORD)
CREATE TABLE FILHO (
NOME STRING NN KEY ORD,
IDADE INTEGER NN,
CPF INTEGER NN,
INTERESSE STRING,
CODIGO INTEGER NN,
SEILA STRING)
INSERT
INTO ALUNO
VALUES (ASSAD, 21, 111, NULO, 91);
INSERT
INTO ALUNO
VALUES (FELIPE, 18, 521, NULO, 92);
INSERT
INTO ALUNO
VALUES (JOSE, 23, 159, NULO, 93);

SELECT NOME,IDADE,CPF
FROM ALUNO
WHERE NOME=FELIPE;
SELECT NOME,CPF
FROM ALUNO
WHERE IDADE>=21;
SELECT NOME
FROM ALUNO;
SELECT NOME
FROM ALUNO JOIN FILHO ON NOME=NAME;
SELECT NOME
FROM ALUNO JOIN FILHO ON NOME=NAME
WHERE CPF=123456;
